// WARNING: This file is automatically generated, manual changes will be overwritten!
namespace MyGameName.Enums;
using EnumFastToStringGenerated;
[EnumGenerator]
public enum GodotInputAction
{
	move_left,
	move_right,
	move_forward,
	move_backwards,
	jump,
	look_up,
	look_down,
	look_left,
	look_right,
	sprint,
	toggle_pause,
	NONE
}