// WARNING: This file is automatically generated, manual changes will be overwritten!
namespace MyGameName.Enums;
using EnumFastToStringGenerated;
[EnumGenerator]
public enum Godot3dPhysicsLayer
{
	world = 1,
	player = 2,
	weapons = 3,
	destructables = 4,
	enemies = 5,
	NONE = 0
}