// WARNING: This file is automatically generated, manual changes will be overwritten!
namespace MyGameName.Enums;
using EnumFastToStringGenerated;
[EnumGenerator]
public enum Godot3dRenderLayer
{
	player_model = 2,
	NONE = 0
}