// WARNING: This file is automatically generated, manual changes will be overwritten!
namespace MyGameName.Enums;
using EnumFastToStringGenerated;
[EnumGenerator]
public enum GodotShaderGlobal
{
	specular_smoothness,
	fresnel_smoothness,
	outline_width,
	outline_color,
	diffuse_curve,
	is_paused,
	player_position,
	wind_speed,
	timescale,
	NONE
}